#DBType: sqlserver
#DriverName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#DatabaseName: JB4DC_SSO_V01
#Url: jdbc:sqlserver://127.0.0.1:1433; DatabaseName=JB4DC_SSO_V01
#User: sa
#Password: sql

#DBType: mysql
#DriverName: com.mysql.cj.jdbc.Driver
#DatabaseName: JB4DC_SSO_V02
#Url: jdbc:mysql://58.51.184.121:6316/JB4DC_SSO_V02?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&autoReconnect=true&failOverReadOnly=false
#User: root
#Password: jb4dc#sz#1234

DBType: mysql
DriverName: com.mysql.cj.jdbc.Driver
DatabaseName: JB4DC_SSO_V05
Url: jdbc:mysql://127.0.0.1:3306/JB4DC_SSO_V05?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&autoReconnect=true&failOverReadOnly=false
User: root
Password: root