#DBType: sqlserver
#DriverName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#DatabaseName: JB4DC_SSO_V01
#Url: jdbc:sqlserver://127.0.0.1:1433; DatabaseName=JB4DC_SSO_V01
#User: sa
#Password: sql

DBType: mysql
DriverName: com.mysql.cj.jdbc.Driver
DatabaseName: JB4DC_SSO_V01
Url: jdbc:mysql://127.0.0.1:3306/JB4DC_SSO_V01?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&autoReconnect=true&failOverReadOnly=false
User: root
Password: root