jb4dc:
  system-caption: 单点登录系统
  system-title: JBuild4DC-单点登录系统
  warning-operation-code: jb4d82
  is-debug: true
  host:
    operation-system: Window
  file:
    root-path: production-files
  sso:
    server:
      name: JB4DC-SSO-WEB-SERVER
      address: https://127.0.0.1:19103
      context-path: /SSOSystem
      view:
        login: /Controller/LoginSSOView
        logout: https://127.0.0.1:19103/SSOSystem/Controller/LogoutSSOView
      excluded:
  builder:
    server:
      name: JB4DC-BUILDER-WEB-SERVER
      context-path: /JB4DCBuilder
  #默认采用http协议提供eureka使用,扩展https附件连接器
  sslConfig:
    enabled: true
    port: 19103
    key-store-type: jks
    key-store-password: jb4d82
    key-alias: jb4dchttps
    key-store: D:/JavaProject/jb4dc/https/jbu4dchttps.jks

spring:
  application:
    name: JB4DC-SSO-WEB-SERVER
    inetutils:
      #客户端的IP
      #preferred-networks: 192.168.3.153
      #preferred-networks: 192.168.18.118
      preferred-networks: 127.0.0.1
  liquibase:
    enabled: false
  thymeleaf:
    prefix: classpath:/static/HTML/
    suffix: .html
    enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

server:
  port: 9103
  servlet:
    session:
      timeout: 7200
    context-path: /SSOSystem

eureka:
  client:
    serviceUrl:
      #服务端的地址
      #defaultZone: http://192.168.3.166:9092/eureka/
      #defaultZone: http://192.168.18.118:9092/eureka/
      defaultZone: http://127.0.0.1:9101/eureka/
      #defaultZone: http://106.55.254.205:9101/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.inetutils.preferred-networks}:${server.port}

logging:
  level:
    com:
      jb4dc:
        system:
          setting:
            dao: TRACE
        sso:
          dao: TRACE
