spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml

jb4dc:
  file:
    root-path: D:/JavaProject/jb4dc/production-files