jb4dc:
  system-caption: 单点登录系统
  system-title: JBuild4DC-单点登录系统
  warning-operation-code: jb4d82
  is-debug: true
  host:
    operation-system: Window
  sso:
    server:
      name: JB4DC-SSO-WEB-SERVER
      address: http://localhost:9101
      context-path: /SSOSystem
      view:
        login: /Controller/LoginSSOView
        logout: /logout
      excluded:

spring:
  application:
    name: JB4DC-SSO-WEB-SERVER
    inetutils:
      #客户端的IP
      #preferred-networks: 192.168.3.153
      #preferred-networks: 192.168.18.118
      preferred-networks: 127.0.0.1
  liquibase:
    enabled: false
  thymeleaf:
    prefix: classpath:/static/HTML/
    suffix: .html
    enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 9101
  servlet:
    session:
      timeout: 7200
    context-path: /SSOSystem

eureka:
  client:
    serviceUrl:
      #服务端的地址
      #defaultZone: http://192.168.3.166:9092/eureka/
      #defaultZone: http://192.168.18.118:9092/eureka/
      defaultZone: http://127.0.0.1:9092/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.inetutils.preferred-networks}:${server.port}

logging:
  level:
    com:
      jb4dc:
        system:
          setting:
            dao: TRACE
        sso:
          dao: TRACE
